version: '3.8'

services:
  backend:
    build: ./backend
    container_name: node-backend
    expose:
      - "5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: react-frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
